-- Migration 008: Add source column to pep_action_items
-- Distinguishes AI-generated items from manually added ones,
-- so re-analysis only deletes AI items (not manual ones).

ALTER TABLE pep_action_items
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'ai'
  CHECK (source IN ('ai', 'manual'));

COMMENT ON COLUMN pep_action_items.source IS 'ai = generated by LLM analysis, manual = added or edited by a user';
